name: st10445500-glms-stack

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "14333:1433"
    volumes:
      - sql-server-data:/var/opt/mssql
    networks:
      - glms-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  backend-api:
    build:
      context: .
      dockerfile: GLMS.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "8080"

      ConnectionStrings__DefaultConnection: "Server=sql-server-db,1433;Database=${MSSQL_DB};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=True"

      Jwt__Key: "${Jwt__Key}"
      Jwt__Issuer: "${Jwt__Issuer}"
      Jwt__Audience: "${Jwt__Audience}"
      Jwt__ExpiresMinutes: "${Jwt__ExpiresMinutes}"

      Uploads__SignedAgreementFolder: "uploads/signed-agreements"

      CurrencyApi__BaseUrl: "${CurrencyApi__BaseUrl}"
      CurrencyApi__TargetCurrency: "${CurrencyApi__TargetCurrency}"
    ports:
      - "5053:8080"
    volumes:
      - contract-uploads:/app/uploads/signed-agreements
    networks:
      - glms-network
    depends_on:
      sql-server-db:
        condition: service_healthy

  frontend-web:
    build:
      context: .
      dockerfile: GLMS.Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "8080"

      ApiSettings__BaseUrl: "http://backend-api:8080/"
    ports:
      - "5004:8080"
    networks:
      - glms-network
    depends_on:
      backend-api:
        condition: service_started

volumes:
  sql-server-data:
  contract-uploads:

networks:
  glms-network:
    driver: bridge
